lib: add type checking to IP address macros
Noticed that IPV4_ADDR_CMP, IPV4_ADDR_SAME and IPV4_ADDR_COPY
macros lacked type checking (same for the IPv6 versions). Added
this and fixed up the resulting compile problems. There were
a few real bugs.
bgp_route.c had a bug that I don't know how to properly fix:
  bgp_route.c: In function ‘bgp_announce_check’:
  bgp_route.c:789: error: ‘struct in_addr’ has no member named ‘__in6_u’
  bgp_route.c:789: error: ‘struct in_addr’ has no member named ‘__in6_u’
I deleted the offending code, but someone that knows BGP needs to
look into this and figure out what to do.

Signed-off-by: Denis Ovsienko <infrastation@yandex.ru>

1. Additional modifications were made to the following functions to address
compilation issues against the current source tree:
* prefix_same()
* ospf_abr_nssa_am_elected()
* rtadv_send_packet()
* rtadv_rdnss_lookup()
* babel_anm_lookup()
* babel_auth_got_source_address()

2. IPv6 macros were changed to use s6_addr instead of __in6_u.__u6_addr8